"""In-memory response cache keyed by document content hash."""

from __future__ import annotations

import hashlib
from typing import Any


class ResponseCache:
    """In-memory cache for analysis results keyed by document content hash.

    Prevents redundant Gemini API calls when the same document is analyzed
    multiple times within a session. Because the key is derived from the
    file bytes rather than the session ID, uploads of the same file from
    different sessions also benefit from the cache.

    Attributes:
        _store: Internal dictionary mapping cache keys to cached values.
    """

    def __init__(self) -> None:
        """Initialize the cache with an empty store."""
        self._store: dict[str, Any] = {}

    def make_key(self, file_bytes: bytes, operation: str) -> str:
        """Generate a deterministic cache key from file content and operation type.

        Args:
            file_bytes: Raw bytes of the uploaded document.
            operation: Operation label (e.g. ``"full"``, ``"simplify"``).

        Returns:
            Hexadecimal SHA-256 digest prefixed with the operation label.
        """
        digest = hashlib.sha256(file_bytes).hexdigest()
        return f"{operation}:{digest}"

    def get(self, key: str) -> Any | None:
        """Retrieve a cached result.

        Args:
            key: Cache key generated by :meth:`make_key`.

        Returns:
            The cached value, or ``None`` if the key is not present.
        """
        return self._store.get(key)

    def set(self, key: str, value: Any) -> None:
        """Store a result in the cache.

        Args:
            key: Cache key generated by :meth:`make_key`.
            value: The result to cache.
        """
        self._store[key] = value

    def clear(self) -> None:
        """Clear all cached entries, releasing memory."""
        self._store.clear()


# Module-level singleton shared across all requests in this process.
response_cache = ResponseCache()
